Rocket launch UI test
EllaGogo/mobile-assignment pull request #3
Opened 2024-12-18 17:26 UTC by nikolduchanova

TODO: Description

2024-12-18 18:36 UTC, EllaGogo requested changes
Overall dobry za mna, len par mensich komentov ;)

2024-12-18 18:36 UTC, EllaGogo commented on Solution/iOS/RocketApp/Features/Sources/Login/AccessibilityKeys+Login.swift
> +    public static let username = "usernameFieldID"
nazov musi byt na oboch stranach stejny, do toho nazvu musis zakomponovat co to je za typ. Napr pro username je typ textField:
usernameTextField = "usernameTextFieldID"

2024-12-18 18:36 UTC, EllaGogo commented on Solution/iOS/RocketApp/Features/Sources/RocketDetail/RocketDetailView.swift
> +            trailing: Button(.launch) {
spatne odsazeni

2024-12-18 18:36 UTC, EllaGogo commented on Solution/iOS/RocketApp/Features/Sources/RocketLaunch/RocketLaunchView.swift
> +          .accessibilityIdentifier(AccessibilityKeys.RocketLaunch.rocketImage)
spatne odsazeni, no new line pod tym pls

2024-12-18 18:36 UTC, EllaGogo commented on Solution/iOS/RocketApp/Features/Sources/RocketLaunch/RocketLaunchView.swift
> +          .accessibilityIdentifier(AccessibilityKeys.RocketLaunch.rocketImage)
mozes si to cele oznacit a dat control+i a malo by ti to sformatovat

2024-12-18 18:36 UTC, EllaGogo commented on Solution/iOS/RocketApp/Features/Sources/RocketList/RocketListView.swift
> -
vratit zpatky empty radek

2024-12-18 18:36 UTC, EllaGogo commented on Solution/iOS/RocketApp/Features/Sources/Login/AccessibilityKeys+Login.swift
> +    public static let username = "usernameFieldID"
to prosim plati pre vsetky identifiers v celom PR

2024-12-18 18:36 UTC, EllaGogo commented on Solution/iOS/RocketAppUITests/Screens/LoginScreen.swift
> +  func enterUsername(_ username: String) -> Self {
enter(username: String) to iste potom dal, Swift preferuje tuto syntax, mrkni na best practices

2024-12-18 18:36 UTC, EllaGogo commented on Solution/iOS/RocketAppUITests/Screens/RocketListScreen.swift
> +  func countRocketCells() -> Self {
Natvrdo pouzite literaly su hrich :D tym myslim 4 pouzite natvrdo v metode. A taky ten nazev prosim zmenit.

2024-12-18 18:36 UTC, EllaGogo commented on Solution/iOS/RocketAppUITests/Screens/RocketListScreen.swift
> +    print("Number of rocket cells displayed: \(rocketCells.count)")
printy pryc

2024-12-18 18:36 UTC, EllaGogo commented on Solution/iOS/RocketAppUITests/Screens/RocketListScreen.swift
> +  func checkRocketNames(_ expectedRocketNames: [String]) -> Self {
Zacala by som test tym ze rocketNames ma stejny pocet polozek jako expectedRocketNames.
Zosortit obe tie polia podla abecedy.

a pak nieco na styl

```
zip(rocketNames, expectedRocketNames).forEach { name, expectedName
    XCTAssert ze se to rovna
}
```

neskusala som to zbuildit, mozno sa s tym budes musiet trochu pohrat, tady je dokumentace na zip https://developer.apple.com/documentation/swift/zip(_:_:)

2024-12-18 18:36 UTC, EllaGogo commented on Solution/iOS/RocketAppUITests/Screens/RocketListScreen.swift
> +  func checkRocketNames(_ expectedRocketNames: [String]) -> Self {
otazka jestli to vubec testovat, protoze je to public API, ktore sa moze kedykolvek zmenit a pak ti to bude zbytocne failovat

2024-12-18 18:36 UTC, EllaGogo commented on Solution/iOS/RocketAppUITests/Utils/TestConstants.swift
> +  enum LoginDetails{
LoginCredentials a chybi ti tam mezera

2024-12-18 18:36 UTC, EllaGogo commented on Solution/iOS/RocketAppUITests/Utils/TestConstants.swift
> +   public static let username = "astronaut1"
preco je to public?

2024-12-20 11:57 UTC, nikolduchanova commented on Solution/iOS/RocketAppUITests/Screens/LoginScreen.swift
> +    XCTAssert(loginTitle.waitForExistence(timeout: 5), "Login title did not appear within the timeout.")
custom error message prosím pryč, všude

2024-12-20 11:57 UTC, nikolduchanova commented on Solution/iOS/RocketAppUITests/Utils/TestConstants.swift
> +  enum LoginDetails{
plus špatně odsazené - LoginDetails vs Rockets

2024-12-20 11:57 UTC, nikolduchanova commented on Solution/iOS/RocketAppUITests/Tests/RocketLaunchTest.swift
> +      .checkRocketTitle()
odstranit breakpointy všude prosím

2024-12-20 11:57 UTC, nikolduchanova commented on Solution/iOS/RocketAppUITests/Screens/RocketListScreen.swift
> +  func tapFirstRocketCell() -> Self {
udělala bych spíš obecnou funkci něco jako goToRocketDetail a vybírala si podle indexu v testu, jakou raketku otevřu

2024-12-20 11:57 UTC, nikolduchanova commented on Solution/iOS/RocketAppUITests/Screens/RocketListScreen.swift
> +  func countRocketCells() -> Self {
pojďme to udělat i pro timeouty, stejně jako test constants a přidala bych je před interakcí s jakýmkoli elementem

2024-12-20 11:57 UTC, nikolduchanova commented on Solution/iOS/RocketAppUITests/Screens/RocketListScreen.swift
> +    XCTAssert(rocketCells.firstMatch.waitForExistence(timeout: 5), "Rocket cells did not appear within the timeout.")
špatně použitá firstMatch property  - "Use the firstMatch property when you know that there can only be one possible match for an element query." 

nevybíráš první raketku, ale první načtenou

2024-12-20 11:57 UTC, nikolduchanova commented on Solution/iOS/RocketAppUITests/Screens/RocketDetailScreen.swift
> +    launchButton = app.navigationBars.buttons[AccessibilityKeys.RocketDetail.launchButton]
proč přidáváš ještě navigationBars?

2024-12-20 11:57 UTC, nikolduchanova commented on Solution/iOS/RocketAppUITests/Screens/RocketListScreen.swift
> +  func checkRocketNames(_ expectedRocketNames: [String]) -> Self {
vzhledem k tomu bych upravila scénář na přihlášení, přechod do detailu první raketky a launchnutí

2024-12-20 11:57 UTC, nikolduchanova commented on Solution/iOS/RocketAppUITests/Tests/RocketLaunchTest.swift
> +      .checkRocketImage()
zkontrolovala bych spíš Launch title

2025-01-07 12:21 UTC, nikolduchanova commented on Solution/iOS/RocketAppUITests/Screens/RocketListScreen.swift
> +    let firstRocketCell = rocketCellArrows.element(boundBy: index)
goToRocketDeatil a upravit firstRocketCell název, který teď už nedává smysl

2025-01-07 12:21 UTC, nikolduchanova commented on Solution/iOS/RocketAppUITests/Utils/TestConstants.swift
> +  enum Timeouts {
pro Timeouts zvlášť file prosím

2025-01-07 12:21 UTC, nikolduchanova commented on Solution/iOS/RocketAppUITests/Screens/RocketListScreen.swift
> +  func goToRocket(atIndex index: Int) -> Self {
nechala bych jen index

2025-01-07 12:21 UTC, nikolduchanova commented on Solution/iOS/RocketApp/Features/Sources/Login/AccessibilityKeys+Login.swift
> +    public static let titleText = "titleTextID"
není typ staticText?

2025-01-07 12:21 UTC, nikolduchanova commented on Solution/iOS/RocketAppUITests/Tests/RocketLaunchTest.swift
> +final class TestRocketLaunch: BaseTestCase {
TestRocketLaunch x RocketLaunchTest, musí to být stejně
Stačí jen RocketLaunch

2025-01-07 12:21 UTC, nikolduchanova commented on Solution/iOS/RocketApp/Features/Sources/RocketList/RocketListView.swift
> +          .accessibilityIdentifier(AccessibilityKeys.RocketList.rocketCell)
rocketCell ID přiřazuješ na button viz logy:
Button, 0x103f30120, {{20.0, 293.0}, {353.0, 71.7}}, identifier: 'rocketCellID'

2025-01-07 12:21 UTC, nikolduchanova commented on Solution/iOS/RocketAppUITests/Screens/LoginScreen.swift
> +    usernameField = app.textFields[AccessibilityKeys.Login.usernameTextField]
asi mi přijde zvláštní přiřazení usernameTextField ID do usernameField konstanty

2025-01-13 14:27 UTC, nikolduchanova commented on Solution/iOS/RocketAppUITests/Screens/LoginScreen.swift
> +    usernameField = app.textFields[AccessibilityKeys.Login.usernameTextField]
usernameTextField = app.textFields[AccessibilityKeys.Login.usernameTextField]
passwordSecureTextField = app.secureTextFields[AccessibilityKeys.Login.passwordSecureField]

2025-01-13 14:32 UTC, nikolduchanova commented on Solution/iOS/RocketApp/Features/Sources/Login/AccessibilityKeys+Login.swift
> +    public static let titleText = "titleTextID"
rocketTitleTextID, AccessibilityKeys.Login.titleText, nezměnil jsi na staticText u všech

2025-01-13 14:33 UTC, nikolduchanova commented on Solution/iOS/RocketApp/Features/Sources/Login/AccessibilityKeys+Login.swift
> +    public static let titleText = "titleTextID"
a změnit u ostatních accessibility keys +název (+RocketDetail apod.)

2025-01-13 14:35 UTC, nikolduchanova commented on Solution/iOS/RocketApp/Features/Sources/Login/AccessibilityKeys+Login.swift
> +    public static let titleText = "titleTextID"
a není konzistentní
    - **public** **static** **let** rocketTitleText = "rocketTitleTextID"
    X
        
        **public** **static** **let** titleStaticText = "titleStaticTextID" u Loginu

2025-01-13 14:37 UTC, nikolduchanova commented on Solution/iOS/RocketAppUITests/Screens/RocketListScreen.swift
> +    let firstRocketCell = rocketCellArrows.element(boundBy: index)
zvážila bych název rocket místo rocketArrow

2025-01-14 09:53 UTC, nikolduchanova commented on Solution/iOS/RocketAppUITests/Screens/LoginScreen.swift
> +    usernameField = app.textFields[AccessibilityKeys.Login.usernameTextField]
bude opraveno nazpět

2025-01-22 08:19 UTC, EllaGogo approved these changes

2025-01-22 09:40 UTC, merged